=== adam-coster/adam-coster/projects/site/src/routes/blog/post.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "Blog Post",
	"type": "object",
	"required": ["slug", "title", "description", "tags", "publishedAt"],
	"properties": {
		"slug": {
			"type": "string",
			"description": "The unique identifier for the blog post"
		},
		"title": {
			"type": "string",
			"maxLength": 75
		},
		"description": {
			"type": "string",
			"maxLength": 175
		},
		"canonical": {
			"type": "string",
			"format": "uri"
		},
		"tags": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/tag"
			}
		},
		"legacySlug": { "type": "string" },
		"editedAt": {
			"type": "string",
			"format": "date-time"
		},
		"publishedAt": {
			"type": "string",
			"format": "date-time"
		},
		"recipe": {
			"type": "object",
			"required": ["name", "description", "image"],
			"properties": {
				"name": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"image": {
					"type": "string",
					"format": "uri"
				},
				"recipeInstructions": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/howToStep"
					}
				},
				"recipeIngredient": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"prepTime": {
					"$ref": "#/definitions/duration"
				},
				"cookTime": {
					"$ref": "#/definitions/duration"
				},
				"totalTime": {
					"$ref": "#/definitions/duration"
				}
			}
		}
	},
	"definitions": {
		"duration": {
			"type": "string",
			"pattern": "PT[0-9]+[HMS]"
		},
		"howToStep": {
			"type": "object",
			"required": ["@type", "text"],
			"properties": {
				"@type": { "const": "HowToStep" },
				"text": { "type": "string" }
			}
		},
		"tag": {
			"enum": [
				"adhd",
				"apple",
				"authentication",
				"autism",
				"beginners",
				"binary",
				"biology",
				"brains",
				"business",
				"coffee",
				"communication",
				"computer-science",
				"cookies",
				"cors",
				"critique",
				"css",
				"data",
				"definition",
				"devops",
				"discuss",
				"docker",
				"documentation",
				"email",
				"encoding",
				"ergonomics",
				"evolution",
				"experiments",
				"expressjs",
				"gamedev",
				"google",
				"health",
				"html",
				"http",
				"javascript",
				"jsdoc",
				"json",
				"learn",
				"life",
				"linux",
				"marketing",
				"math",
				"media",
				"mental-health",
				"mochajs",
				"motivation",
				"neurodiversity",
				"node",
				"notion",
				"npm",
				"permissions",
				"phd",
				"philosophy",
				"privilege",
				"productivity",
				"programming",
				"python",
				"recipe",
				"science",
				"security",
				"serialization",
				"simulation",
				"statistics",
				"tdd",
				"testing",
				"tools",
				"tutorial",
				"typescript",
				"video",
				"vscode",
				"webdev",
				"windows",
				"writing"
			]
		}
	}
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/geb-wondrousness-python/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "geb-wondrousness-python",
	"title": "\"GÃ¶del, Escher, Bach\": Wondrousness in Python",
	"description": "In GEB the Tortoise and Achilles describe a number property they call \"Wondrousness\". It creates a fascinating graph.\n",
	"publishedAt": "2011-01-15T00:00:00.000Z",
	"legacySlug": "python-geb-and-wondrousness",
	"tags": ["math", "learn", "simulation", "programming", "python"]
}
