=== adam-coster/adam-coster/projects/site/src/routes/blog/post.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"title": "Blog Post",
	"type": "object",
	"required": ["slug", "title", "description", "tags", "publishedAt"],
	"properties": {
		"slug": {
			"type": "string",
			"description": "The unique identifier for the blog post"
		},
		"title": {
			"type": "string",
			"maxLength": 75
		},
		"description": {
			"type": "string",
			"maxLength": 175
		},
		"canonical": {
			"type": "string",
			"format": "uri"
		},
		"tags": {
			"type": "array",
			"items": {
				"$ref": "#/definitions/tag"
			}
		},
		"legacySlug": { "type": "string" },
		"editedAt": {
			"type": "string",
			"format": "date-time"
		},
		"publishedAt": {
			"type": "string",
			"format": "date-time"
		},
		"recipe": {
			"type": "object",
			"required": ["name", "description", "image"],
			"properties": {
				"name": {
					"type": "string"
				},
				"description": {
					"type": "string"
				},
				"image": {
					"type": "string",
					"format": "uri"
				},
				"recipeInstructions": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/howToStep"
					}
				},
				"recipeIngredient": {
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"prepTime": {
					"$ref": "#/definitions/duration"
				},
				"cookTime": {
					"$ref": "#/definitions/duration"
				},
				"totalTime": {
					"$ref": "#/definitions/duration"
				}
			}
		}
	},
	"definitions": {
		"duration": {
			"type": "string",
			"pattern": "PT[0-9]+[HMS]"
		},
		"howToStep": {
			"type": "object",
			"required": ["@type", "text"],
			"properties": {
				"@type": { "const": "HowToStep" },
				"text": { "type": "string" }
			}
		},
		"tag": {
			"enum": [
				"adhd",
				"apple",
				"authentication",
				"autism",
				"beginners",
				"binary",
				"biology",
				"brains",
				"business",
				"coffee",
				"communication",
				"computer-science",
				"cookies",
				"cors",
				"critique",
				"css",
				"data",
				"definition",
				"devops",
				"discuss",
				"docker",
				"documentation",
				"email",
				"encoding",
				"ergonomics",
				"evolution",
				"experiments",
				"expressjs",
				"gamedev",
				"google",
				"health",
				"html",
				"http",
				"javascript",
				"jsdoc",
				"json",
				"learn",
				"life",
				"linux",
				"marketing",
				"math",
				"media",
				"mental-health",
				"mochajs",
				"motivation",
				"neurodiversity",
				"node",
				"notion",
				"npm",
				"permissions",
				"phd",
				"philosophy",
				"privilege",
				"productivity",
				"programming",
				"python",
				"recipe",
				"science",
				"security",
				"serialization",
				"simulation",
				"statistics",
				"tdd",
				"testing",
				"tools",
				"tutorial",
				"typescript",
				"video",
				"vscode",
				"webdev",
				"windows",
				"writing"
			]
		}
	}
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/looper-allele-frequency-problem/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "looper-allele-frequency-problem",
	"title": "Allele frequency problem in \"Looper\"",
	"description": "Time travel is always a nonsense generator, but \"Looper\" kicks it up a notch with impossibly rapid evolution.\n",
	"publishedAt": "2013-01-12T07:55:00.402Z",
	"legacySlug": "allele-frequency-problem-in-looper",
	"tags": ["science", "biology", "evolution", "media", "critique"]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/image-correction-microscopy/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "image-correction-microscopy",
	"title": "Image Correction Microscopy",
	"description": "Fluorescence microscopy images are plagued with background noise. The standard approach to correcting for this is insufficient.\n",
	"editedAt": "2021-11-28T00:00:00.000Z",
	"publishedAt": "2014-05-31T00:00:00.000Z",
	"legacySlug": "image-correction-in-fluorescence-microscopy",
	"tags": ["science", "biology", "phd"]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/cloning-ligation-multiple-inserts/meta.json
{
	"$schema": "../post.schema.json",
	"slug": "cloning-ligation-multiple-inserts",
	"title": "Cloning trick: ligation of multiple inserts",
	"description": "Stitching multiple DNA inserts together through standard cloning yields terrible results. But you can amplify the rare successes!\n",
	"editedAt": "2013-02-26T00:00:00.000Z",
	"publishedAt": "2011-07-11T00:00:00.000Z",
	"legacySlug": "cloning-trick-ligation-of-multiple-inserts",
	"tags": [
		"science",
		"biology",
		"experiments",
		"tools",
		"productivity",
		"learn"
	]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/coffee-tonic/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "coffee-tonic",
	"title": "Super Simple Coffee Tonic",
	"description": "All you need is cold coffee, a tasty syrup, and tonic water.",
	"publishedAt": "2024-04-21T19:54:02.293Z",
	"tags": ["coffee", "recipe"],
	"recipe": {
		"name": "Super Simple Coffee Tonic",
		"description": "All you need is cold coffee, a tasty syrup, and tonic water.",
		"image": "https://adamcoster.com/images/coffee/coffee-tonic-ingredients.jpg",
		"recipeIngredient": [
			"4oz (120ml) cold coffee",
			"2oz (60ml) tonic water",
			"1/2oz (15ml) simple syrup",
			"ice"
		],
		"prepTime": "PT5M",
		"cookTime": "PT5M",
		"recipeInstructions": [
			{
				"@type": "HowToStep",
				"text": "Combine cold coffee, tonic water, and simple syrup."
			}
		]
	}
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/coffee-cold-brew/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "coffee-cold-brew",
	"title": "Super Simple Cold Brew Coffee",
	"description": "All you need is a jar, a tea infuser, and some ground coffee.",
	"publishedAt": "2024-04-21T19:54:02.293Z",
	"tags": ["coffee", "recipe"],
	"recipe": {
		"name": "Super Simple Cold Brew Coffee",
		"description": "All you need is a jar, a tea infuser, and some ground coffee.",
		"image": "https://adamcoster.com/images/coffee/coffee-infusion.jpg",
		"recipeIngredient": [
			"5 tbsp (30g) coffee beans, coarsely ground",
			"12 oz (350ml) cool water"
		],
		"prepTime": "PT5M",
		"cookTime": "PT18H",
		"recipeInstructions": [
			{
				"@type": "HowToStep",
				"text": "Grind coffee beans coarsely and add to the tea infuser."
			},
			{
				"@type": "HowToStep",
				"text": "Place the tea infuser into a mason jar."
			},
			{
				"@type": "HowToStep",
				"text": "Pour room temperature or colder water over the coffee, refilling periodically as it passes through the grounds, until it is close to the top."
			},
			{
				"@type": "HowToStep",
				"text": "Cover, place in the refrigerator, and let sit for 18+ hours."
			}
		]
	}
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/birthday-problem-python/meta.json
{
	"$schema": "../post.schema.json",
	"slug": "birthday-problem-python",
	"title": "The \"Birthday Problem\" simulated with Python",
	"description": "There's better than a 50% chance that 2 of any 25 random people will share the same birthday. That's hard to believe. Let's simulate it!\n",
	"publishedAt": "2011-07-13T00:00:00.000Z",
	"legacySlug": "python-shared-birthdays",
	"tags": ["math", "learn", "statistics", "simulation", "programming", "python"]
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/simple-syrup/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "simple-syrup",
	"title": "Simple Syrup",
	"description": "Add flavor and sweetness to cocktails, mocktails, and anything else.",
	"publishedAt": "2024-04-21T19:54:02.293Z",
	"tags": ["recipe"],
	"recipe": {
		"name": "Simple Syrup",
		"description": "Add flavor and sweetness to cocktails, mocktails, and anything else.",
		"image": "https://adamcoster.com/images/coffee/coffee-tonic.jpg",
		"recipeIngredient": ["250ml water", "250g sugar"],
		"prepTime": "PT5M",
		"cookTime": "PT10M",
		"recipeInstructions": [
			{
				"@type": "HowToStep",
				"text": "Add sugar to water."
			},
			{
				"@type": "HowToStep",
				"text": "Heat until sugar dissolves."
			},
			{
				"@type": "HowToStep",
				"text": "Add any other flavors you want."
			},
			{
				"@type": "HowToStep",
				"text": "Cover and store in the refrigerator."
			}
		]
	}
}

=== adam-coster/adam-coster/projects/site/src/routes/blog/(posts)/monty-hall-python/meta.json
{
	"$schema": "../../post.schema.json",
	"slug": "monty-hall-python",
	"title": "The Monty Hall problem modeled in Python",
	"description": "The Monty Hall problem is a classic example of how difficult statistical reasoning can be. Let's simulate it in Python.\n",
	"publishedAt": "2011-02-20T00:00:00.000Z",
	"legacySlug": "python-monty-hall-modeling",
	"tags": ["math", "learn", "statistics", "simulation", "programming", "python"]
}
